# Test your FastAPI endpoints

###

GET http://127.0.0.1:8000/maregraphe/getMaregraphe
Accept: application/json

###

GET http://127.0.0.1:8000/maregrapheMeta/getMeta/3
Accept: application/json

###

GET http://127.0.0.1:8000/meta/getMetaId
Accept: application/json

###

POST http://127.0.0.1:8000/maregrapheMeta/addMeta/3&ville&coin
Accept: application/json

###

POST http://127.0.0.1:8000/maregraphe/addMaregraphe/1&Coincoin&0&0
Accept: application/json

###

POST http://127.0.0.1:8000/meta/addMeta/aaa&aaa&3
Accept: application/json

###

PUT http://127.0.0.1:8000/maregrapheMeta/updateMeta/3&ville&Brest
Accept: application/json

###

PUT http://127.0.0.1:8000/meta/updateMeta/ville&Nom%20de%20la%20ville&50
Accept: application/json

###

DELETE http://127.0.0.1:8000/maregrapheMeta/deleteMeta/3&ville
Accept: application/json

###

DELETE http://127.0.0.1:8000/maregrapheMeta/deleteMeta/2
Accept: application/json

###

DELETE http://127.0.0.1:8000/meta/deleteMeta/aaa
Accept: application/json