# Test your FastAPI endpoints

###

GET http://127.0.0.1:8000/maregraphe
Accept: application/json

###

GET http://127.0.0.1:8000/metadonnee/3
Accept: application/json

###

GET http://127.0.0.1:8000/getMetaId/
Accept: application/json

###

POST http://127.0.0.1:8000/addMeta/3&ville&coin
Accept: application/json

###

PUT http://127.0.0.1:8000/updateMeta/3&ville&Brest
Accept: application/json

###

DELETE http://127.0.0.1:8000/deleteMeta/3&ville
Accept: application/json