POST http://127.0.0.1:8000/connexion/token
Content-Type: application/json

{
  "username":"johndoe",
  "password":"secret"
}
> {% client.global.set("token", response.body.access_token) %}

###

GET http://127.0.0.1:8000/partenaire/getPartenaire
Authorization: Bearer {{token}}
Accept: application/json

###

GET http://127.0.0.1:8000/partenaire/sort/nom&True
Authorization: Bearer {{token}}
Accept: application/json

###

POST http://127.0.0.1:8000/partenaire/addPartenaire/-1&isen&logo_SHOM.png
Authorization: Bearer {{token}}
Accept: application/json

{
"url": "https://isen-brest.fr/"
}

###

PUT http://127.0.0.1:8000/partenaire/updatePartenaire/-1&isen2&logo_SHOM2.png
Authorization: Bearer {{token}}
Accept: application/json

{
"url" : "https://www.shom.fr/"
}

###

DELETE http://127.0.0.1:8000/partenaire/deletePartenaire/-1
Authorization: Bearer {{token}}
Accept: application/json