POST http://127.0.0.1:8000/connexion/token
Content-Type: application/json

{
  "username":"johndoe",
  "password":"secret"
}
> {% client.global.set("token", response.body.access_token) %}

###

GET http://127.0.0.1:8000/partenaire/getPartenaire
Authorization: Bearer {{token}}
Accept: application/json

###

GET http://127.0.0.1:8000/partenaire/getPartenaireMaregraphe/50
Authorization: Bearer {{token}}
Accept: application/json

###

PUT http://127.0.0.1:8000/partenaire/updatePartenaire/50&shom2&logo_SHOM2.png
Authorization: Bearer {{token}}
Accept: application/json

{
"url" : "https://www.shom2.fr/"
}

###