POST http://127.0.0.1:8000/connexion/token
Content-Type: application/json

{
  "username":"johndoe",
  "password":"secret"
}
> {% client.global.set("token", response.body.access_token) %}

###

GET http://127.0.0.1:8000/partenaireMaregrape/getPartenaireMaregraphe/50
Authorization: Bearer {{token}}
Accept: application/json

###

GET http://127.0.0.1:8000/partenaireMaregrape/sort/50&libelle&true
Authorization: Bearer {{token}}
Accept: application/json